---
title: "Example Presentation"
output: slidy_presentation
---

## Overview

This document has code embedded throughout. In the next section we will create a visualization using the already loaded dataset `cryptodata`:
```{r, warning=F, message=F}
datatable(eth_data, rownames = FALSE, 
          options(list(lengthMenu = c(4, 5, 6))))
```

## Price Chart

```{r, warning=F, message=F, echo=F}
eth_chart
```


## Interactive Chart

```{r, warning=F, message=F, echo=F}
interactive_chart
```

## Python Code Example

```{python}
import pandas as pd
# Create the Python object from R
df = r.cryptodata
# Show the new Python dataframe
df
```

## One more Python example

Press on `w` on your keyboard to make the presentation wider. Press `f` to fullscreen.

```{python}
import numpy as np
# Create a new field based on the ask_1_price value:
df['price_percentile'] = np.where(df['ask_1_price'] > np.percentile(df['ask_1_price'], 50),
                            'upper 50th percentile of prices', 
                            'lower 50th percentile of prices')
# Show modified dataframe:
df[['symbol', 'ask_1_price', 'price_percentile']]
```

## [Back to Gallery](https://r-markdown-gallery.org)

<!-- TODO - Add note about going back to gallery -->

```{r}
knitr::include_url("https://r-markdown-gallery.org")
```

