name: Run R Markdown Examples
on: [push]

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
          crayon.enabled: 'FALSE'
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-3-
      - name: Run script and render documents
        run: |
          #install.packages('rmarkdown')
          #install.packages('pacman')
          install.packages('renv')
          renv::consent(provided = TRUE)
          renv::restore()
          source('script.R')
          rmarkdown::render('presentations/ioslides.Rmd', envir = env)
        shell: Rscript {0}
      - name: Commit and push files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Refresh R Markdown examples from CI automated process" -a
          git push https://ries9112:${{secrets.GITHUB_TOKEN}}@github.com/ries9112/R-Markdown-Gallery.git HEAD:main --force
